name       : gitbatch
version    : 0.4.3
release    : 1
source     :
    - https://github.com/isacikgoz/gitbatch/archive/v0.4.3.tar.gz : cc40862f2335afaee8c4c6d687143cc006b49575116cd7d217c87d1b01c9dd22
license    : MIT
component  : programming.tools
summary    : Manage your git repositories in one place
description: |
    Managing multiple git repositories is easier than ever. I (was) often end up working on many directories and manually pulling updates etc. To make this routine faster, I created a simple tool to handle this job. Although the focus is batch jobs, you can still do de facto micro management of your git repositories (e.g add/reset, stash, commit etc.).
networking : yes    
builddeps  :
    - git
    - golang
rundeps    :
    - git      
build      : |
    GOOS=linux GOARCH=amd64 go build -o dist/gitbatch
install    : |
    install -Dm00755 dist/gitbatch $installdir/usr/bin/gitbatch

